import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {VT323} from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "NSA",
  description: "Generated by create next app",
};

const vt323 = VT323({
  subsets: ['latin'],
  weight:["400"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${geistSans.variable} ${geistMono.variable} ${vt323.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
